/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import DAO.DAOUser;
import DB.ConnectionFactory;
import Model.User;
import com.mycompany.hacerdedo.punto0.SystemLogic;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebaa
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public static LoginFrame lf;
    private User user;
    private DAOUser daoUser;
    
    public void setUser(User user) {
        this.user = user;
    }

    public User getUser() {
        return user;
    }
    
    public LoginFrame() {
        initComponents();
        SystemLogic.initSystemLogic();
        daoUser = new DAOUser();
        
        this.setLocationRelativeTo(null);
    }
    
    public static LoginFrame initLoginFrame()
    {
        if (lf == null) {
            lf = new LoginFrame();
        }
        return lf;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerButton = new javax.swing.JButton();
        nameAppLabel1 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        userJLabel = new javax.swing.JLabel();
        passJLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setText("Registrarse");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        nameAppLabel1.setBackground(new java.awt.Color(255, 51, 51));
        nameAppLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        nameAppLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameAppLabel1.setText("INSERT NAME APP HERE !!");

        userTextField.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        userJLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        userJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userJLabel.setText("Usuario");

        passJLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        passJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passJLabel.setText("Costraseña");

        loginButton.setBackground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Ingresar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(loginButton))
                    .addComponent(userTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameAppLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameAppLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registerButton))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        if (this.userTextField.getText().isEmpty() && this.jPasswordField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan datos");
        } else {
            try {
                if (SystemLogic.initSystemLogic().login(this.userTextField.getText(), this.jPasswordField.getText()))
                {
                    //JOptionPane.showMessageDialog(this, Integer.parseInt(userTextField.getText()));
                    this.user = this.daoUser.get(Integer.parseInt(this.userTextField.getText().toString()));
                    UserFrame.initUserFrame();
                    UserFrame.initUserFrame().setUser(user);
                    this.setVisible(false);
                    
                    this.userTextField.setText("");
                    this.jPasswordField.setText("");
                    
                    
                } else
                {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectas ");
                }

            }catch (SQLException qle)
            {
                JOptionPane.showMessageDialog(this, "Error, verifique datos ");
            }
            /*
        Connection con = ConnectionFactory.getConnection();
        try {
            Statement select = con.createStatement();
            String login = String.format("SELECT * FROM users WHERE ci = '%s' AND password = '%s'", 
                    this.userTextField.getText(), this.jPasswordField.getText());
            
            ResultSet rs = select.executeQuery(login);
            int i = 0;
            while(rs.next()) {
                i++;
            }
            
            if (i == 1) {
            JOptionPane.showMessageDialog(this, "Usted a ingresado buen hombre");
            }
            else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }
        } catch(SQLException sqle) {
            JOptionPane.showMessageDialog(this, "Error, verifique datos ");
        }finally {
            ConnectionFactory.closeConnection(con);
        }*/
        }   
    // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        RegisterFrame.initRegisterFrame();
        RegisterFrame.initRegisterFrame().setVisible(true);
        
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField;
    protected javax.swing.JButton loginButton;
    private javax.swing.JLabel nameAppLabel1;
    private javax.swing.JLabel passJLabel;
    protected javax.swing.JButton registerButton;
    private javax.swing.JLabel userJLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
